host = "데이터베이스 url 주소"
user = "데이터베이스 user 이름"
password = "데이터베이스 password"
database = "데이터베이스 이름"
aladin_open_api_ttbkey = "알라딘 Open API 신청 key"
aladin_open_api_search_url = "알라딘 Open API 도서 검색 url"
aladin_open_api_detail_url = "알라딘 Open API 도서 상세 조회 url"
